# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  checks: write
  pull-requests: write
  issues: write
  packages: write

jobs:
  pass:
    name: I pass
    runs-on: ubuntu-latest
    steps:
      - name: Live
        shell: bash
        run: |
          echo "Hi"

  fail:
    name: I don't fail
    runs-on: ubuntu-latest
    steps:
      - name: Die
        shell: bash
        run: |
          exit 0

  done:
    name: Done
    if: ${{ always() }}
    needs:
      - pass
      - fail
    runs-on: ubuntu-latest
    steps:
      - name: show
        shell: bash
        run: |
          echo "${{ contains(needs.*.result, 'failure') }}"

      - name: Write
        shell: bash
        if: ${{ contains(needs.*.result, 'failure') }}
        run: |

          exit 1
